-- ============================================================
-- 01_spine.sql
-- Core identity tables: person, household, person_household
--
-- These tables form the structural spine of the system.
-- They are intentionally minimal — only fields that are
-- stable and rarely change belong here. Everything else
-- lives in fact tables under the relevant domain.
-- ============================================================


-- ------------------------------------------------------------
-- TYPES
-- ------------------------------------------------------------

CREATE TYPE gender_type AS ENUM ('male', 'female');


-- ------------------------------------------------------------
-- TABLES
-- ------------------------------------------------------------

CREATE TABLE person (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name        TEXT        NOT NULL,
  preferred_name   TEXT,
  date_of_birth    DATE,
  gender           gender_type NOT NULL,
  user_identifier  TEXT        UNIQUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_person_user_identifier
  ON person(user_identifier)
  WHERE user_identifier IS NOT NULL;

-- ------------------------------------------------------------

CREATE TABLE household (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------

CREATE TABLE person_household (
  person_id     UUID        NOT NULL REFERENCES person(id),
  household_id  UUID        NOT NULL REFERENCES household(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (person_id, household_id)
);

CREATE INDEX idx_person_household_household
  ON person_household(household_id);


-- ------------------------------------------------------------
-- FUNCTIONS & TRIGGERS
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER person_updated_at
  BEFORE UPDATE ON person
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER household_updated_at
  BEFORE UPDATE ON household
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();


-- ------------------------------------------------------------
-- COMMENTS — TABLES
-- ------------------------------------------------------------

COMMENT ON TABLE person IS
  'Core identity record for a person in the system.
   Intentionally minimal — only stable, rarely-changing fields live here.
   All additional personal information (address, phone, preferences etc.)
   lives in fact tables under the personal_details domain.
   A person may or may not be a system user — family members who are
   tracked but do not log in have user_identifier = null.';

COMMENT ON TABLE household IS
  'A household groups one or more persons together.
   Represents a shared living unit or family group.
   Household-level information (address, shared expenses, utilities)
   lives in fact tables under the household domain.
   Example: "The Sharma Family", "Raj and Priya"';

COMMENT ON TABLE person_household IS
  'Junction table for the many-to-many relationship between
   persons and households. A person can belong to multiple
   households (e.g. splitting time between two homes).
   A household can contain multiple persons.
   Membership has no expiry — if a person leaves a household,
   the row is deleted.';


-- ------------------------------------------------------------
-- COMMENTS — TYPES
-- ------------------------------------------------------------

COMMENT ON TYPE gender_type IS
  'Gender of a person. Intentionally simple enum.
   Can be extended with ALTER TYPE gender_type ADD VALUE if needed.
   Example values: male, female';


-- ------------------------------------------------------------
-- COMMENTS — COLUMNS: person
-- ------------------------------------------------------------

COMMENT ON COLUMN person.id IS
  'Unique identifier for the person. UUID generated by the database.
   Used as foreign key in all related tables.
   Example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"';

COMMENT ON COLUMN person.full_name IS
  'Full legal or commonly used name of the person.
   Single field to accommodate non-Western naming conventions
   where first/last split is not always meaningful.
   Example: "Rajesh Sharma", "Priya Sharma", "Li Wei"';

COMMENT ON COLUMN person.preferred_name IS
  'Nickname or name the person commonly goes by.
   Used by the chatbot when addressing the person conversationally.
   Null if the person goes by their full name.
   Example: full_name="Rajesh Sharma", preferred_name="Raj"';

COMMENT ON COLUMN person.date_of_birth IS
  'Date of birth of the person. Used for age calculations,
   health reminders, and birthday notifications.
   Nullable — may not be known for all persons.
   Example: 1985-06-15';

COMMENT ON COLUMN person.gender IS
  'Gender of the person. Used for kinship resolution
   (determining correct relational terms like bua vs mama).
   See gender_type enum for allowed values.';

COMMENT ON COLUMN person.user_identifier IS
  'Login identifier for persons who can access the system.
   Typically an email address. Must be unique across all persons.
   Null for family members who are data subjects but not system users
   (e.g. children, elderly parents being tracked by another user).
   Example: "raj.sharma@gmail.com"';

COMMENT ON COLUMN person.created_at IS
  'Timestamp when this person record was created.
   Set automatically by the database. Never updated.';

COMMENT ON COLUMN person.updated_at IS
  'Timestamp when this person record was last updated.
   Maintained automatically by the person_updated_at trigger.
   Only changes when spine fields are updated — fact table
   changes do not affect this timestamp.';


-- ------------------------------------------------------------
-- COMMENTS — COLUMNS: household
-- ------------------------------------------------------------

COMMENT ON COLUMN household.id IS
  'Unique identifier for the household. UUID generated by the database.
   Example: "b2c3d4e5-f6a7-8901-bcde-f12345678901"';

COMMENT ON COLUMN household.name IS
  'Human-readable name for the household.
   Typically the family name or a descriptive label.
   Example: "The Sharma Family", "Raj and Priya", "Sharma Household"';

COMMENT ON COLUMN household.created_at IS
  'Timestamp when this household record was created.
   Set automatically by the database. Never updated.';

COMMENT ON COLUMN household.updated_at IS
  'Timestamp when this household record was last updated.
   Maintained automatically by the household_updated_at trigger.';


-- ------------------------------------------------------------
-- COMMENTS — COLUMNS: person_household
-- ------------------------------------------------------------

COMMENT ON COLUMN person_household.person_id IS
  'Foreign key to the person who is a member of the household.';

COMMENT ON COLUMN person_household.household_id IS
  'Foreign key to the household the person belongs to.';

COMMENT ON COLUMN person_household.created_at IS
  'Timestamp when this membership was established.
   Useful for knowing when a person joined a household.';
